<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" encoding="UTF-8" indent="yes" />

  <xsl:template match="/">
    <html lang="en">
      <head>
        <title>XML Sitemap</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
          body {
            margin: 0;
            background: #fff;
            color: #242628;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            font-size: 14px;
            line-height: 1.5;
          }

          main {
            max-width: 960px;
            margin: 36px auto;
            padding: 0 24px;
          }

          h1 {
            margin: 0 0 8px;
            font-size: 28px;
            font-weight: 600;
          }

          p {
            margin: 0 0 24px;
            color: #4a4f55;
          }

          a {
            color: #1a73e8;
            text-decoration: none;
          }

          a:hover {
            text-decoration: underline;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            border: 1px solid #dfe3e8;
          }

          th,
          td {
            padding: 10px 12px;
            border-bottom: 1px solid #dfe3e8;
            text-align: left;
            vertical-align: top;
          }

          th {
            background: #f6f8fa;
            font-weight: 600;
          }

          tr:last-child td {
            border-bottom: 0;
          }

          .number,
          .date,
          .frequency {
            white-space: nowrap;
          }
        </style>
      </head>
      <body>
        <main>
          <h1>XML Sitemap</h1>
          <p>This is a sitemap generated by <a href="https://toolbox.curioboxapp.info/">Curiobox Toolbox</a> to allow search engines to discover this site's content.</p>

          <xsl:choose>
            <xsl:when test="sitemap:sitemapindex">
              <table>
                <thead>
                  <tr>
                    <th>Sitemap</th>
                    <th>Last Modified</th>
                  </tr>
                </thead>
                <tbody>
                  <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                    <tr>
                      <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc" /></a></td>
                      <td class="date"><xsl:value-of select="translate(substring(sitemap:lastmod, 1, 16), 'T', ' ')" /></td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
            </xsl:when>
            <xsl:otherwise>
              <table>
                <thead>
                  <tr>
                    <th>URL</th>
                    <th>Last Modified</th>
                    <th>Change Frequency</th>
                    <th>Priority</th>
                  </tr>
                </thead>
                <tbody>
                  <xsl:for-each select="sitemap:urlset/sitemap:url">
                    <tr>
                      <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc" /></a></td>
                      <td class="date"><xsl:value-of select="translate(substring(sitemap:lastmod, 1, 16), 'T', ' ')" /></td>
                      <td class="frequency"><xsl:value-of select="sitemap:changefreq" /></td>
                      <td class="number"><xsl:value-of select="sitemap:priority" /></td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
            </xsl:otherwise>
          </xsl:choose>
        </main>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
