import { useMemo } from 'react';
import { useTranslations } from 'next-intl';
import { Tool } from '@/types';

export function useTools(locale: string) {
  const t = useTranslations();

  const tools: Tool[] = useMemo(() => [
    {
      id: 'json-formatter',
      title: t('tools.jsonFormatter.title'),
      description: t('tools.jsonFormatter.description'),
      category: 'formatters',
      icon: 'Braces',
      href: `/${locale}/tools/json-formatter`,
    },
    {
      id: 'xml-formatter',
      title: t('tools.xmlFormatter.title'),
      description: t('tools.xmlFormatter.description'),
      category: 'formatters',
      icon: 'FileCode',
      href: `/${locale}/tools/xml-formatter`,
    },
    {
      id: 'base64',
      title: t('tools.base64.title'),
      description: t('tools.base64.description'),
      category: 'encoders',
      icon: 'Lock',
      href: `/${locale}/tools/base64`,
    },
    {
      id: 'url-encoder',
      title: t('tools.urlEncoder.title'),
      description: t('tools.urlEncoder.description'),
      category: 'encoders',
      icon: 'Link',
      href: `/${locale}/tools/url-encoder`,
    },
    {
      id: 'uuid-generator',
      title: t('tools.uuidGenerator.title'),
      description: t('tools.uuidGenerator.description'),
      category: 'generators',
      icon: 'Fingerprint',
      href: `/${locale}/tools/uuid-generator`,
    },
    {
      id: 'hash-generator',
      title: t('tools.hashGenerator.title'),
      description: t('tools.hashGenerator.description'),
      category: 'generators',
      icon: 'Shield',
      href: `/${locale}/tools/hash-generator`,
    },
    {
      id: 'password-generator',
      title: t('tools.passwordGenerator.title'),
      description: t('tools.passwordGenerator.description'),
      category: 'generators',
      icon: 'Key',
      href: `/${locale}/tools/password-generator`,
    },
    {
      id: 'qr-generator',
      title: t('tools.qrGenerator.title'),
      description: t('tools.qrGenerator.description'),
      category: 'utilities',
      icon: 'QrCode',
      href: `/${locale}/tools/qr-generator`,
    },
    {
      id: 'color-converter',
      title: t('tools.colorConverter.title'),
      description: t('tools.colorConverter.description'),
      category: 'converters',
      icon: 'Palette',
      href: `/${locale}/tools/color-converter`,
    },
    {
      id: 'regex-tester',
      title: t('tools.regexTester.title'),
      description: t('tools.regexTester.description'),
      category: 'text',
      icon: 'Search',
      href: `/${locale}/tools/regex-tester`,
    },
    {
      id: 'string-tools',
      title: t('tools.stringTools.title'),
      description: t('tools.stringTools.description'),
      category: 'text',
      icon: 'Type',
      href: `/${locale}/tools/string-tools`,
    },
    {
      id: 'text-compare',
      title: t('tools.textCompare.title'),
      description: t('tools.textCompare.description'),
      category: 'text',
      icon: 'FileText',
      href: `/${locale}/tools/text-compare`,
    },
    {
      id: 'markdown-preview',
      title: t('tools.markdownPreview.title'),
      description: t('tools.markdownPreview.description'),
      category: 'formatters',
      icon: 'FileCode',
      href: `/${locale}/tools/markdown-preview`,
    },
    {
      id: 'jwt-decoder',
      title: t('tools.jwtDecoder.title'),
      description: t('tools.jwtDecoder.description'),
      category: 'encoders',
      icon: 'Key',
      href: `/${locale}/tools/jwt-decoder`,
    },
    {
      id: 'timestamp-converter',
      title: t('tools.timestampConverter.title'),
      description: t('tools.timestampConverter.description'),
      category: 'converters',
      icon: 'Clock',
      href: `/${locale}/tools/timestamp-converter`,
    },
    {
      id: 'lorem-generator',
      title: t('tools.loremGenerator.title'),
      description: t('tools.loremGenerator.description'),
      category: 'generators',
      icon: 'FileText',
      href: `/${locale}/tools/lorem-generator`,
    },
    {
      id: 'case-converter',
      title: t('tools.caseConverter.title'),
      description: t('tools.caseConverter.description'),
      category: 'text',
      icon: 'Type',
      href: `/${locale}/tools/case-converter`,
    },
    {
      id: 'html-formatter',
      title: t('tools.htmlFormatter.title'),
      description: t('tools.htmlFormatter.description'),
      category: 'formatters',
      icon: 'Code',
      href: `/${locale}/tools/html-formatter`,
    },
    {
      id: 'css-minifier',
      title: t('tools.cssMinifier.title'),
      description: t('tools.cssMinifier.description'),
      category: 'utilities',
      icon: 'Minimize2',
      href: `/${locale}/tools/css-minifier`,
    },
    {
      id: 'sql-formatter',
      title: t('tools.sqlFormatter.title'),
      description: t('tools.sqlFormatter.description'),
      category: 'formatters',
      icon: 'Database',
      href: `/${locale}/tools/sql-formatter`,
    },
    {
      id: 'image-to-base64',
      title: t('tools.imageToBase64.title'),
      description: t('tools.imageToBase64.description'),
      category: 'converters',
      icon: 'Image',
      href: `/${locale}/tools/image-to-base64`,
    },
    {
      id: 'number-base-converter',
      title: t('tools.numberBaseConverter.title'),
      description: t('tools.numberBaseConverter.description'),
      category: 'converters',
      icon: 'Binary',
      href: `/${locale}/tools/number-base-converter`,
    },
    {
      id: 'word-counter',
      title: t('tools.wordCounter.title'),
      description: t('tools.wordCounter.description'),
      category: 'text',
      icon: 'FileText',
      href: `/${locale}/tools/word-counter`,
    },
    {
      id: 'line-sorter',
      title: t('tools.lineSorter.title'),
      description: t('tools.lineSorter.description'),
      category: 'text',
      icon: 'ArrowDownAZ',
      href: `/${locale}/tools/line-sorter`,
    },
    {
      id: 'duplicate-remover',
      title: t('tools.duplicateRemover.title'),
      description: t('tools.duplicateRemover.description'),
      category: 'text',
      icon: 'Trash2',
      href: `/${locale}/tools/duplicate-remover`,
    },
    {
      id: 'html-entity-encoder',
      title: t('tools.htmlEntityEncoder.title'),
      description: t('tools.htmlEntityEncoder.description'),
      category: 'encoders',
      icon: 'Code',
      href: `/${locale}/tools/html-entity-encoder`,
    },
    {
      id: 'json-to-csv',
      title: t('tools.jsonToCsv.title'),
      description: t('tools.jsonToCsv.description'),
      category: 'converters',
      icon: 'FileSpreadsheet',
      href: `/${locale}/tools/json-to-csv`,
    },
    {
      id: 'csv-to-json',
      title: t('tools.csvToJson.title'),
      description: t('tools.csvToJson.description'),
      category: 'converters',
      icon: 'FileJson',
      href: `/${locale}/tools/csv-to-json`,
    },
    {
      id: 'yaml-formatter',
      title: t('tools.yamlFormatter.title'),
      description: t('tools.yamlFormatter.description'),
      category: 'formatters',
      icon: 'FileCode',
      href: `/${locale}/tools/yaml-formatter`,
    },
    {
      id: 'credit-card-validator',
      title: t('tools.creditCardValidator.title'),
      description: t('tools.creditCardValidator.description'),
      category: 'utilities',
      icon: 'CreditCard',
      href: `/${locale}/tools/credit-card-validator`,
    },
    {
      id: 'pdf-to-word',
      title: t('tools.pdfToWord.title'),
      description: t('tools.pdfToWord.description'),
      category: 'pdf',
      icon: 'FileOutput',
      href: `/${locale}/tools/pdf-to-word`,
    },
    {
      id: 'pdf-merge',
      title: t('tools.pdfMerge.title'),
      description: t('tools.pdfMerge.description'),
      category: 'pdf',
      icon: 'Combine',
      href: `/${locale}/tools/pdf-merge`,
    },
    {
      id: 'pdf-protect',
      title: t('tools.pdfProtect.title'),
      description: t('tools.pdfProtect.description'),
      category: 'pdf',
      icon: 'Lock',
      href: `/${locale}/tools/pdf-protect`,
    },
    {
      id: 'pdf-to-image',
      title: t('tools.pdfToImage.title'),
      description: t('tools.pdfToImage.description'),
      category: 'pdf',
      icon: 'ImageIcon',
      href: `/${locale}/tools/pdf-to-image`,
    },
  ], [t, locale]);

  const categories = useMemo(() => [
    { id: 'all', label: t('common.allTools') },
    { id: 'formatters', label: t('categories.formatters') },
    { id: 'encoders', label: t('categories.encoders') },
    { id: 'generators', label: t('categories.generators') },
    { id: 'converters', label: t('categories.converters') },
    { id: 'text', label: t('categories.text') },
    { id: 'utilities', label: t('categories.utilities') },
    { id: 'pdf', label: t('categories.pdf') },
  ], [t]);

  return { tools, categories };
}
